/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 登录 */
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/products': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 商品列表（分页 + 关键字搜索） */
    get: operations['getProductList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/products/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 商品详情 */
    get: operations['getProductDetail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 订单列表（分页） */
    get: operations['getOrderList']
    put?: never
    /** 创建订单（下单） */
    post: operations['createOrder']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/orders/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 订单详情 */
    get: operations['getOrderDetail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiError: {
      code: number
      message: string
    }
    LoginRequest: {
      username: string
    }
    Product: {
      id: number
      name: string
      price: number
      originalPrice: number
      image: string
      description: string
      category: string
      stock: number
      rating: number
      reviews: number
      tags?: string[]
    }
    ProductListResponse: {
      list: components['schemas']['Product'][]
      total: number
      page: number
      pageSize: number
    }
    Category: {
      id: number
      name: string
      parentId: number | null
    }
    /** @enum {string} */
    OrderStatus: 'pending' | 'paid' | 'shipped' | 'completed' | 'cancelled'
    OrderItem: {
      productId: number
      productName: string
      productImage: string
      price: number
      quantity: number
    }
    ShippingAddress: {
      name: string
      phone: string
      province: string
      city: string
      district: string
      detail: string
    }
    Order: {
      id: string
      status: components['schemas']['OrderStatus']
      items: components['schemas']['OrderItem'][]
      totalAmount: number
      address: components['schemas']['ShippingAddress']
      phone: string
      createdAt: string
      updatedAt: string
    }
    OrderDetailResponse: {
      order: components['schemas']['Order']
    }
    OrderListResponse: {
      list: components['schemas']['Order'][]
      total: number
      page: number
      pageSize: number
    }
    CheckoutRequest: {
      items: {
        productId: number
        quantity: number
      }[]
      address: components['schemas']['ShippingAddress']
    }
    CheckoutResponse: {
      orderId: string
      totalAmount: number
    }
    LoginResponseEnvelope: {
      code: number
      message: string
      data: {
        token: string
      }
    }
    ProductListResponseEnvelope: {
      code: number
      message: string
      data: components['schemas']['ProductListResponse']
    }
    ProductResponseEnvelope: {
      code: number
      message: string
      data: components['schemas']['Product']
    }
    OrderListResponseEnvelope: {
      code: number
      message: string
      data: components['schemas']['OrderListResponse']
    }
    OrderDetailResponseEnvelope: {
      code: number
      message: string
      data: components['schemas']['OrderDetailResponse']
    }
    CheckoutResponseEnvelope: {
      code: number
      message: string
      data: components['schemas']['CheckoutResponse']
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description 登录成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponseEnvelope']
        }
      }
    }
  }
  getProductList: {
    parameters: {
      query?: {
        page?: number
        pageSize?: number
        keyword?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 商品列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductListResponseEnvelope']
        }
      }
    }
  }
  getProductDetail: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 商品详情 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductResponseEnvelope']
        }
      }
    }
  }
  getOrderList: {
    parameters: {
      query?: {
        page?: number
        pageSize?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 订单列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderListResponseEnvelope']
        }
      }
    }
  }
  createOrder: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CheckoutRequest']
      }
    }
    responses: {
      /** @description 下单结果 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CheckoutResponseEnvelope']
        }
      }
    }
  }
  getOrderDetail: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 订单详情 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderDetailResponseEnvelope']
        }
      }
    }
  }
}
